#!/usr/bin/env perl
#this script will take a set of directories generated by convert_xglcd_to_font -export and a font size, and generate a new directory with characters matching that size
use warnings;
use strict;
use Getopt::Long;
use Data::Dumper;
use Cwd;

my $height;
GetOptions("height=i" => \$height);
my $origdir = cwd();
my $above = 0;
my $below = 0;
#read all character dimensions
my %char;
foreach my $dir (@ARGV) {
    chdir $dir;
    my @chars = glob("*_*_*_*");
    $char{$dir} = {};
    foreach my $ch (@chars) {
        my($num, $w, $a, $b) = split(/_/, $ch);
        $char{$dir}{$num} = {above => $a, below => $b, total => $a + $b, width => $w, name => $ch};
    }
    chdir $origdir;
}
#print Dumper(\%char);
chdir $origdir;
#find largest below from 1st font
foreach my $c (values %{ $char{$ARGV[0]} }) {
    $below = $c->{below} if ($c->{total} < $height && $c->{below} > $below);
}
$above = $height - $below;
#build final character set
my %final;
foreach my $dir (@ARGV) {
    foreach my $ch (keys %{ $char{$ARGV[0]} }) {
        $final{$ch} ||= undef;
        next unless($char{$dir}{$ch});
        if(! $final{$ch} && $char{$dir}{$ch}{above} <= $above && $char{$dir}{$ch}{below} <= $below) {
            $final{$ch} = {dir => $dir, name => $char{$dir}{$ch}{name} };
        }
    }
}

#write set
mkdir("$ARGV[0]_merged");
foreach my $ch (sort keys %final) {
    if(! $final{$ch}) {
        print "WARNING: No character found for $ch that fits size requirements\n";
    } else {
        system("cp $final{$ch}{dir}/$final{$ch}{name} $ARGV[0]_merged/");
    }
}
$height = $above + $below;
system("echo $height > $ARGV[0]_merged/height");
