#ifndef _UNIVERSALTX_TARGET_H_
#define _UNIVERSALTX_TARGET_H_

#define PROTO_HAS_CYRF6936
#define PROTO_HAS_A7105
#define PROTO_HAS_CC2500
#define PROTO_HAS_NRF24L01

#define HAS_MULTIMOD_SUPPORT 0
#define SWITCH_ADDRESS 0xFFFFFFFF

#define _USART USART4
#endif /*_UNIVERSALTX_TARGET_H_ */
