#ifndef _UNIVERSALTX_TARGET_H_
#define _UNIVERSALTX_TARGET_H_

#define PROTO_HAS_CYRF6936
#define PROTO_HAS_A7105
#define PROTO_HAS_CC2500
#define PROTO_HAS_NRF24L01
#define PROTO_HAS_PPM_OUT 0
#define PROTO_HAS_USB_OUT 0

#define DISCOVERY    0 //FIXME: Disable this!

#define HAS_MULTIMOD_SUPPORT 1
#define SWITCH_ADDRESS 0xFFFFFFFF
#define HAS_CYRF_RESET 0

#define _USART USART2
#endif /*_UNIVERSALTX_TARGET_H_ */
