#!/bin/bash

# Check for machine type
if [ "`uname`" = "Darwin" ]
then
	TTSCMD="say"
	TTSOPT="-o"
	TTSFILEEXT="aiff"
else
	TTSCMD="espeak"
	TTSOPT="-w"
	TTSFILEEXT="wav"
fi

# Test for TTS command existance
command -v $TTSCMD >/dev/null 2>&1
if [ $? != 0 ]
then
	echo "Please install $TTSCMD onto your system"
        exit 1
fi

# Test for lame command existance
command -v lame >/dev/null 2>&1
if [ $? != 0 ]
then
	echo "Please install lame onto your system"
        exit 1
fi

FILENUM=1
IDX=100
TMPFILE="/tmp/speechidx.tmp"
cp /dev/null $TMPFILE
SPEECHDIR="mp3"
mkdir $SPEECHDIR 2>/dev/null
rm -f ${SPEECHDIR}/* >/dev/null 2>&1
rm -f models/model*.map >/dev/null 2>&1

for INFILE in models/model*Alert.txt
do
	echo "Processing file $INFILE..."
	OUTFILE=`echo $INFILE | sed -e 's/Alert\.txt/\.map/'`
	rm $OUTFILE 2>/dev/null
	
	while read LINE
	do
		SWITCH=`echo $LINE | cut -d':' -f1`
		SWITCH=`echo $SWITCH | sed -e 's/^ *//;s/ *$//' | tr [a-z] [A-Z]`
		MSG=`echo $LINE | cut -d':' -f2`
		MSG=`echo $MSG | sed -e 's/^ *//;s/ *$//' | tr [a-z] [A-Z]`
		R=`grep "@${MSG}@" $TMPFILE`
		if [ $? != 0 ]
		then
			IDXTEXT=`printf '%04d' $IDX`
			echo "${SWITCH}:${IDXTEXT}" >> $OUTFILE
			$TTSCMD $TTSOPT ${SPEECHDIR}/${IDXTEXT}.${TTSFILEEXT} "$MSG"
			lame --quiet ${SPEECHDIR}/${IDXTEXT}.${TTSFILEEXT} ${SPEECHDIR}/${IDXTEXT}.mp3
			rm ${SPEECHDIR}/${IDXTEXT}.${TTSFILEEXT}
			echo "@${MSG}@:${IDXTEXT}" >> $TMPFILE
			IDX=`expr $IDX + 1`
		else
			echo "${SWITCH}:`echo $R|cut -d':' -f2`" >> $OUTFILE
		fi
	done < $INFILE
done
rm $TMPFILE
