/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define SUPC_IRQHandler supc_isr
#define RSTC_IRQHandler rstc_isr
#define RTC_IRQHandler rtc_isr
#define RTT_IRQHandler rtt_isr
#define WDT_IRQHandler wdt_isr
#define PMC_IRQHandler pmc_isr
#define EEFC_IRQHandler eefc_isr
#define RESERVED0_IRQHandler reserved0_isr
#define UART0_IRQHandler uart0_isr
#define UART1_IRQHandler uart1_isr
#define RESERVED1_IRQHandler reserved1_isr
#define PIOA_IRQHandler pioa_isr
#define PIOB_IRQHandler piob_isr
#define PIOC_IRQHandler pioc_isr
#define USART0_IRQHandler usart0_isr
#define USART1_IRQHandler usart1_isr
#define RESERVED2_IRQHandler reserved2_isr
#define RESERVED3_IRQHandler reserved3_isr
#define RESERVED4_IRQHandler reserved4_isr
#define TWI0_IRQHandler twi0_isr
#define TWI1_IRQHandler twi1_isr
#define SPI_IRQHandler spi_isr
#define RESERVED5_IRQHandler reserved5_isr
#define TC0_IRQHandler tc0_isr
#define TC1_IRQHandler tc1_isr
#define TC2_IRQHandler tc2_isr
#define TC3_IRQHandler tc3_isr
#define TC4_IRQHandler tc4_isr
#define TC5_IRQHandler tc5_isr
#define ADC_IRQHandler adc_isr
#define DACC_IRQHandler dacc_isr
#define PWM_IRQHandler pwm_isr
